name: copilot-setup-steps

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'npm'
        cache-dependency-path: onnxjs/package-lock.json

    - name: Install npm dependencies
      run: cd onnxjs && npm install

    - name: Build and run ML.NET project
      run: cd ml.net/InclusiveCodeReviews.Convert && dotnet run

    - name: Run tests
      run: cd onnxjs && npm test
