name: train ML.NET model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.x
    - name: install mlnet
      run: dotnet tool install --global mlnet
    - name: train
      run: mlnet classification --dataset ml.net/MLConsoleApp/test.csv --label-col 1 --has-header true --train-time 60
    - name: archive
      uses: actions/upload-artifact@v2
      with:
        name: SampleClassification
        path: SampleClassification
        if-no-files-found: error
